version: '3'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    container_name: 4b-sale-page
    networks:
      - 4b-sale-page_network

networks:
  4b-sale-page_network:
